---
title: "advds4bme Final Project"
author: "Adam Kenet and Karl Lee"
date: "4/2021"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r}
# Advanced Data Science for BME
# Adam Kenet and Karl Lee
# April 2021
# Final Project
```


```{r setup, echo=FALSE, message=FALSE, include=FALSE, warning=FALSE}
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(plotly)
library(shiny)
library(lubridate)
library(googleVis)
library(leaflet)
library(geosphere)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
# root = "C:/Users/adamk/Desktop/Flight Delay Predictor"
# setwd(paste0(root,"/flight_delay_predictor"))

# import individual data files
base_url <- 'https://raw.githubusercontent.com/akenet/flight_delay_predictor/main/Data/flights'

dat <- read_csv('https://raw.githubusercontent.com/akenet/flight_delay_predictor/main/Data/flights0.csv')
for(i in 53:60){
  dat2load <- read_csv(paste0(base_url,i,".csv"), col_names = FALSE) %>% 
    rename('FL_DATE' = 'X1',
           'OP_CARRIER' = 'X2',
           'ORIGIN' = 'X3',
           'DEST' = 'X4',
           'CRS_DEP_TIME' = 'X5',
           'DEP_DELAY' = 'X6')
  
  # combine individual data files
  dat <- rbind(dat, dat2load)
  
  # remove individual data file
  rm(dat2load)
}
# change column names
dat <- rename(dat, 'DATE' = 'FL_DATE',
              'AIRLINE' = 'OP_CARRIER',
              'DEPARTURE' = 'ORIGIN',
              'ARRIVAL' = 'DEST',
              'DEP_TIME' = 'CRS_DEP_TIME')

# remove year from dates
dat <- mutate(dat, DATE=format(as.Date(DATE), "%m-%d"))

# convert date from chr to date
dat$DATE <- as.Date(dat$DATE, format = "%m-%d")

# add column with departure time of day
dat <- dat %>%
  mutate(TIME_OF_DAY = case_when(DEP_TIME >= 1800 ~ 'Evening/Night',
                                 DEP_TIME >= 1200 ~ 'Afternoon',
                                 DEP_TIME >= 600 ~ 'Late Morning',
                                 TRUE ~ 'Early Morning'))

# add column for if delayed more than 10 minutes
dat <- dat %>%
  mutate(DELAYED_BOOL = case_when(DEP_DELAY > 10 ~ 1,
                                 TRUE ~ 0))

# add column for day number instead of date
dat <- dat %>% 
  mutate(DAY_NUM = yday(DATE))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# import data on airports in data
airport_data <- read_csv('https://raw.githubusercontent.com/akenet/flight_delay_predictor/main/airports_filtered.csv')

# add column that includes name and IATA code together
airport_data <- airport_data %>% mutate(full = paste0(airport_data$NAME, ' (', airport_data$IATA, ')'))

# alphabetize the data by airport name
airport_data <- airport_data[order(airport_data$full),]
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
# create unique lists
airlines = sort(unique(dat$AIRLINE))
airports = sort(unique(airport_data$full))

arrivals = sort(unique(dat$ARRIVAL))
departures = sort(unique(dat$DEPARTURE))
```


Column {.sidebar data-width=300}
-----------------------------------------------------------------------

### Your Flight:
```{r}
hr()
# which airline
selectInput(inputId = "airline", label = "Airline:",
            choices = airlines,
            selected = 'American Airlines')

# which departure airport
selectInput(inputId = "departure", label = "Departure Airport:",
            choices = airports,
            selected = 'LaGuardia Airport (LGA)')

# which arrival airport
selectInput(inputId = "arrival", label = "Arrival Airport:",
            choices = airports,
            selected = 'Los Angeles International Airport (LAX)')

# which departure date
dateInput(inputId = "date", label = "Departure Date:",
          value = NULL,
          format = "mm-dd")

# which departure time
numericInput(inputId = "time",
          label = "Departure Time (please enter in military time. eg. 1:45 pm would be 1345.)",
          value = 1345)

# selectInput(inputId = "time", label = "Departure Time:",
#             choices = list("12:00 am - 5:59 am" = "Early Morning",
#                            "6:00 am - 11:59 am" = "Late Morning",
#                            "12 pm - 5:59 pm" = "Afternoon",
#                            "6:00 pm - 11:59 pm" = "Evening/Night"),
#             selected = 'Late Morning')

actionButton("run", label = "Submit")
```

Column {data-width=400}
-----------------------------------------------------------------------

#### Our Model Predicts:
```{r}
p0 <- eventReactive(input$run, {
  # Filter by airline
  whichAirline <- filter(dat, AIRLINE == input$airline)
  
  # Determine which departure airport was chosen
  dep <- input$departure
  dep <- substr(dep, nchar(dep)-3, nchar(dep)-1) # get only the IATA code
  
  # check to make sure there is data
  num_data1 <- sum(whichAirline$DEPARTURE == dep)
  
  good = 0
  if (num_data1 > 0){ # if there is data from departure airport
    # Filter by departure airport
    whichDeparture <- filter(whichAirline, DEPARTURE == dep)
    good = 1
  }
  
  if (good == 1) { # if have data from both airline and departure airport
    # filtered data for training model (only chosen airline from chosen departure city)
    dat2train <- whichDeparture
    
    # train model on filtered data
    myModel <- lm(DEP_DELAY ~ DEP_TIME + DAY_NUM, data = dat2train)
    
    # predict using user input for departure time and day of year
    b0 <- coef(myModel)[1]
    b1 <- coef(myModel)[2]
    b2 <- coef(myModel)[3]
    
    
    predicted_delay <- b0 + (b1*input$time) + (b2*yday(input$date))
    
    
    
    # set up theme
    my_theme <- theme_classic() +
      theme(text = element_text(size = 14),
            plot.title = element_text(hjust = 0.5),
            axis.title.x = element_text(margin = margin(10,0,0,0)),
            axis.title.y = element_text(margin = margin(0,10,0,0)),
            axis.text.x = element_text(margin = margin(5,0,0,0)),
            axis.text.y = element_text(margin = margin(0,5,0,0)))
    
    # create base plot
    myPlot <- myPlot <- ggplot() +
      annotate("text", x = 4, y = 25, size = 8,
               label=paste0("Your flight will be delayed by ~", round(predicted_delay,2), " minutes.")) +
      theme_void()
  } else { # if don't have data from departure airport on airline
    myPlot <- ggplot() +
      annotate("text", x = 4, y = 25, size = 8,
               label=paste0("No Data Available on ", input$airline, "from ", input$deptarture)) +
      theme_void()
  }
  
  # make interactive
  plotly_build(myPlot)
  
})

renderPlotly({
  p0()
})
```


#### Historical Delays for Your Specific Flight
##### (Airline, Route, Day, Time)
```{r}
p1 <- eventReactive(input$run, {

  # Determine which date was chosen
  date <- substr(input$date, 6, 10) # only want month and day
  date <- as.Date(date, format = "%m-%d") # convert date from chr to date
  whichDate <- filter(dat, DATE == date)

  # Filter by airline
  whichAirline <- filter(whichDate, AIRLINE == input$airline)

  # Determine which departure airport was chosen
  dep <- input$departure
  dep <- substr(dep, nchar(dep)-3, nchar(dep)-1) # get only the IATA code

  # check to make sure there is data
  num_data1 <- sum(whichAirline$DEPARTURE == dep)

  good = 0
  if (num_data1 > 0){ # if there is data from departure airport
    # Filter by departure airport
    whichDeparture <- filter(whichAirline, DEPARTURE == dep)
    good = 1

    # Determine which arrival airport was chosen
    arr <- input$arrival
    arr <- substr(arr, nchar(arr)-3, nchar(arr)-1) # get only the IATA code

    # check to make sure there is data
    num_data2 <- sum(whichDeparture$ARRIVAL == arr)

    if (num_data2 > 0){ # if there is data from arrival airport
      # Filter by arrival airport
      whichArrival <- filter(whichDeparture, ARRIVAL == arr)
      good = good + 1 # good=2 if have data from both departure and arrival airport

      # Determine which time was chosen
      time <- input$time

      # convert time into time period
      time <- case_when(DEP_TIME >= 1800 ~ 'Evening/Night',
                                 DEP_TIME >= 1200 ~ 'Afternoon',
                                 DEP_TIME >= 600 ~ 'Late Morning',
                                 TRUE ~ 'Early Morning')
      # if (time >= 1800){
      #   time <- 'Evening/Night'
      # }
      # else if (time >= 1200){
      #   time <- 'Afternoon'
      # }
      # else if (time >= 600){
      #   time <- 'Late Morning'
      # }
      # else {
      #   time <- 'Morning'
      # }

      # check to make sure there is data
      num_data3 <- sum(whichArrival$TIME_OF_DAY == time)

      if (num_data3 > 0){ # if there is data on that route during that time
        whichTime <- filter(whichArrival, TIME_OF_DAY == time)
        good = good + 1 # good=3 if have data on that route during that time

        # calculate percent delayed
        num_flights <- nrow(whichTime) # total number of flights
        num_delayed <- sum(whichTime$DELAYED_BOOL) # number of delayed flights (>10 min)
        frac_delayed <- num_delayed / num_flights
      }
    }
  }

  if (good == 3) { # if have data on that route during that time
    # final data for plotting
    dat2plot <- whichTime

    # set up theme
    my_theme <- theme_classic() +
      theme(text = element_text(size = 14),
            plot.title = element_text(hjust = 0.5),
            axis.title.x = element_text(margin = margin(10,0,0,0)),
            axis.title.y = element_text(margin = margin(0,10,0,0)),
            axis.text.x = element_text(margin = margin(5,0,0,0)),
            axis.text.y = element_text(margin = margin(0,5,0,0)))

    # create base plot
    myPlot <- ggplot() +
      annotate("text", x = 4, y = 25, size = 8,
               label=paste0(round(frac_delayed,4)*100,"% (",num_delayed,"/",num_flights,") delayed more than 10 minutes.")) +
      theme_void()
  } else { # if don't have data from departure/arrival/both airports
    myPlot <- ggplot() +
      annotate("text", x = 4, y = 25, size = 8, label = 'No Data Available At Your Time') +
               # label=paste0('No Data Available in the ', time)) +
      theme_void()
  }

  # make interactive
  plotly_build(myPlot)

})

renderPlotly({
  p1()
})
```

#### Historical Delays For Your Route and Airline
```{r}
p2 <- eventReactive(input$run, {
  # Filter by airline
  whichAirline <- filter(dat, AIRLINE == input$airline)
  
  # Determine which departure airport was chosen
  dep <- input$departure
  dep <- substr(dep, nchar(dep)-3, nchar(dep)-1) # get only the IATA code
  
  # check to make sure there is data
  num_data1 <- sum(whichAirline$DEPARTURE == dep)
  
  good = 0
  if (num_data1 > 0){ # if there is data from departure airport
    # Filter by departure airport
    whichDeparture <- filter(whichAirline, DEPARTURE == dep)
    good = 1
    
    # Determine which arrival airport was chosen
    arr <- input$arrival
    arr <- substr(arr, nchar(arr)-3, nchar(arr)-1) # get only the IATA code
    
    # check to make sure there is data
    num_data2 <- sum(whichDeparture$ARRIVAL == arr)
    
    if (num_data2 > 0){ # if there is data from arrival airport
      # Filter by arrival airport
      whichArrival <- filter(whichDeparture, ARRIVAL == arr)
      good = good + 1 # good=2 if have date from both departure and arrival airport
    }
    
  }
  
  if (good == 2) { # if have data from both departure and arrival airport
    # final data for plotting
    dat2plot <- whichArrival
    
    # set up theme
    my_theme <- theme_classic() +
      theme(text = element_text(size = 14),
            plot.title = element_text(hjust = 0.5),
            axis.title.x = element_text(margin = margin(10,0,0,0)),
            axis.title.y = element_text(margin = margin(0,10,0,0)),
            axis.text.x = element_text(margin = margin(5,0,0,0)),
            axis.text.y = element_text(margin = margin(0,5,0,0)))
    
    # create base plot
    myPlot <- ggplot(dat2plot) +
      geom_point(aes(x=DATE, y=DEP_DELAY, colour=DEP_DELAY > 10)) +
      scale_colour_manual(name = 'Delayed', values = setNames(c('red','green'),c(T,F))) +
  
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%m-%d") +
      ylab('Delay (min)') +
      xlab('Departure Date') +
      my_theme
  } else { # if don't have data from departure/arrival/both airports
    myPlot <- ggplot() +
      annotate("text", x = 4, y = 25, size = 8, label='No Data Available on Your Route+Airline') +
      theme_void()
  }
  
  # make interactive
  plotly_build(myPlot)
  
})

renderPlotly({
  p2()
})
```

#### Your Trip
```{r}
renderLeaflet({
  # filter chosen airports
  lat_long <- filter(airport_data, (airports %in% input$departure) | (airports %in% input$arrival))
  
  arr_lat_long <- filter(airport_data, airports %in% input$arrival)
  dep_lat_long <- filter(airport_data, airports %in% input$departure)
  
  gcIntermediate(c(dep_lat_long$LONG, dep_lat_long$LAT), c(arr_lat_long$LONG, arr_lat_long$LAT), n=100, addStartEnd = TRUE, sp = TRUE) %>%
    leaflet() %>%
    addTiles() %>%
    addMarkers(lat = lat_long$LAT,
               lng = lat_long$LONG,
               popup = paste("<strong>",lat_long$full)) %>%
    addCircles(lat = lat_long$LAT,
               lng = lat_long$LONG,
               weight = 1) %>%
    addPolylines()
})
```